apiVersion: v1
kind: Service
metadata:
  name: attendance-app
  namespace: attendance
  labels:
    app.kubernetes.io/name: attendance-app
    app.kubernetes.io/part-of: attendance-management
spec:
  # クラスタ内とIngressからのみ利用する
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: attendance-app
    app.kubernetes.io/component: application
